Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MvcMovie.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcMovie.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace MvcMovie.Controllers
{
    public class MovieController : Controller
    {
        private AppDbContext _context;
        public List<Movie> lstMovies = null;
        public List<Comments> lstComments = null;
        
        public MovieController(AppDbContext context)
        {
            _context = context;
            
            /*var myJsonString = System.IO.File.ReadAllText("Models/Movie.json");
            lstMovies = JsonConvert.DeserializeObject<List<Movie>>(myJsonString);*/

            /*var myJsonString = System.IO.File.ReadAllText("Models/Comments.json");
            lstComments = JsonConvert.DeserializeObject<List<Comments>>(myJsonString);*/
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _context.Movies.ToListAsync();

            foreach(var movie in movies){
                movie.Images = JsonConvert.DeserializeObject<List<String>>(movie.ImagesJson);
            }

            return View(movies);
        }

        [Authorize]
        public IActionResult Add()
        {
            List<SelectListItem> Generes = new List<SelectListItem>
            {
                new SelectListItem { Value = "Accion", Text = "Accion" },
                new SelectListItem { Value = "Familia", Text = "Familia" },
                new SelectListItem { Value = "Aventura", Text = "Aventura"  },
            };
            
            ViewBag.Generes = Generes;
            return View(new Movie());
        }

        [HttpPost]
        public async Task<IActionResult> Save(Movie model)
        {
            if(ModelState.IsValid) { 
                _context.Movies.Add(model);
                await _context.SaveChangesAsync();
                return View("Index", await _context.Movies.ToListAsync());
            }

            List<SelectListItem> Generes = new List<SelectListItem>
            {
                new SelectListItem { Value = "Accion", Text = "Accion" },
                new SelectListItem { Value = "Familia", Text = "Familia" },
                new SelectListItem { Value = "Aventura", Text = "Aventura"  },
            };
            
            ViewBag.Generes = Generes;
            return View("Add", model);
        }

        public async Task<IActionResult> Details(int Id)
        {
            var movie = await _context.Movies.Where(m => m.Id == Id).Include(m => m.Comments).FirstAsync();
            movie.Images = JsonConvert.DeserializeObject<List<String>>(movie.ImagesJson);

            return View(movie);
        }

        public IActionResult Find(string movie)
        {
            List<Movie> listResultMovie = new List<Movie>();

            foreach (var item in lstMovies)
            {
                if(item.Title.ToLower().Contains(movie.ToLower()))
                    listResultMovie.Add(item);
            }

            return View("Index", listResultMovie);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int Id)
        {
            var movie = await _context.Movies.FindAsync(Id);
            
            if(movie == null)
                return NotFound();

            _context.Remove(movie);
            await _context.SaveChangesAsync();
            return View("Index", await _context.Movies.ToListAsync());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMovie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutCine.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMovieTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/cover.css" />  
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
        <h3 class="masthead-brand">Cover</h3>
        <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="/">Home</a>
            <a class="nav-link" href="#">Features</a>
            <a class="nav-link" href="/Movie">Movie</a>
            <partial name="_LoginPartial" />
        </nav>
        </div>
    </header>

        <main role="main" class="row pb-3">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
            	@RenderSection("LateralDerecho", false)
            </div>
 
            <div class="col-md-12">
            	@RenderSection("AreaInferior", false)
            </div>
        </main>

    <footer class="mastfoot mt-auto">
        <div class="inner">
        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>.</p>
        </div>
    </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/sweetalert.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>